(function(){'use strict';var h=this;function k(a,b){a=a.split(".");var c=h;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b};function l(a){this.type=a;this.target=null}l.prototype.preventDefault=l.prototype.stopPropagation=function(){};var m=function(){var a;"cosh"in Math?a=Math.cosh:a=function(a){a=Math.exp(a);return(a+1/a)/2};return a}();/*

 Latitude/longitude spherical geodesy formulae taken from
 http://www.movable-type.co.uk/scripts/latlong.html
 Licensed under CC-BY-3.0.
*/
function n(a){this.radius=a}function p(a,b){var c=a[1]*Math.PI/180,d=b[1]*Math.PI/180,e=(d-c)/2;a=(b[0]-a[0])*Math.PI/180/2;c=Math.sin(e)*Math.sin(e)+Math.sin(a)*Math.sin(a)*Math.cos(c)*Math.cos(d);return 2*q.radius*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))}
n.prototype.offset=function(a,b,c){var d=a[1]*Math.PI/180;b/=this.radius;var e=Math.asin(Math.sin(d)*Math.cos(b)+Math.cos(d)*Math.sin(b)*Math.cos(c));return[180*(a[0]*Math.PI/180+Math.atan2(Math.sin(c)*Math.sin(b)*Math.cos(d),Math.cos(b)-Math.sin(d)*Math.sin(e)))/Math.PI,180*e/Math.PI]};var q=new n(6370997);var r={};r.degrees=2*Math.PI*q.radius/360;r.ft=.3048;r.m=1;r["us-ft"]=1200/3937;function t(a){this.a=a.code;this.b=a.units;this.i=void 0!==a.f?a.f:this.j;this.c=a.h;var b=u,c=a.code,d=v||window.proj4;if("function"==typeof d&&void 0===b[c]){var e=d.defs(c);if(void 0!==e){void 0===a.h&&(this.c=e.to_meter);void 0===a.units&&(this.b=e.units);var f,g;for(f in b)if(a=d.defs(f),void 0!==a)if(b=w(f),a===e)x([b,this]);else{g=d(f,c);a=g.forward;g=g.inverse;var b=w(b),E=w(this);y(b,E,z(a));y(E,b,z(g))}}}}
t.prototype.j=function(a,b){if("degrees"==this.b)return a;var c=w("EPSG:4326"),d=this.a,c=c.a,e;d in A&&c in A[d]&&(e=A[d][c]);void 0===e&&(e=B);a=[b[0]-a/2,b[1],b[0]+a/2,b[1],b[0],b[1]-a/2,b[0],b[1]+a/2];a=e(a,a,2);e=(p(a.slice(0,2),a.slice(2,4))+p(a.slice(4,6),a.slice(6,8)))/2;a=this.c||r[this.b];void 0!==a&&(e/=a);return e};t.prototype.f=function(a,b){return this.i(a,b)};var u={},A={},v=null;function x(a){C(a);a.forEach(function(b){a.forEach(function(a){b!==a&&y(b,a,D)})})}
function F(a){u[a.a]=a;y(a,a,D)}function C(a){var b=[];a.forEach(function(a){b.push(F(a))})}function y(a,b,c){a=a.a;b=b.a;a in A||(A[a]={});A[a][b]=c}function z(a){return function(b,c,d){var e=b.length;d=void 0!==d?d:2;c=void 0!==c?c:Array(e);var f,g;for(g=0;g<e;g+=d)for(f=a([b[g],b[g+1]]),c[g]=f[0],c[g+1]=f[1],f=d-1;2<=f;--f)c[g+f]=b[g+f];return c}}
function w(a){var b;if(a instanceof t)b=a;else if("string"===typeof a){b=u[a];var c=v||window.proj4;void 0===b&&"function"==typeof c&&void 0!==c.defs(a)&&(b=new t({code:a}),F(b))}return b||null}function B(a,b){if(void 0!==b&&a!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}return a}function D(a,b){if(void 0!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}else a=a.slice();return a};(function(){if(!("HTMLCanvasElement"in window))return!1;try{return document.createElement("CANVAS").getContext("2d")?!0:!1}catch(a){return!1}})();navigator.userAgent.match("CriOS");try{new MouseEvent("click",{buttons:1})}catch(a){};function G(a){t.call(this,{code:a,units:"m",extent:H,global:!0,u:I})}G.prototype=Object.create(t.prototype);G.prototype.constructor=G;G.prototype.f=function(a,b){return a/m(b[1]/6378137)};var J=6378137*Math.PI,H=[-J,-J,J,J],I=[-180,-85,180,85],K="EPSG:3857 EPSG:102100 EPSG:102113 EPSG:900913 urn:ogc:def:crs:EPSG:6.18:3:3857 urn:ogc:def:crs:EPSG::3857 http://www.opengis.net/gml/srs/epsg.xml#3857".split(" ").map(function(a){return new G(a)});
function L(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c){b[e]=J*a[e]/180;var f=6378137*Math.log(Math.tan(Math.PI*(a[e+1]+90)/360));f>J?f=J:f<-J&&(f=-J);b[e+1]=f}return b}function M(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c)b[e]=180*a[e]/J,b[e+1]=360*Math.atan(Math.exp(a[e+1]/6378137))/Math.PI-90;return b};var N=new n(6378137);function O(a,b){t.call(this,{code:a,units:"degrees",extent:P,v:b,global:!0,h:Q,u:P})}O.prototype=Object.create(t.prototype);O.prototype.constructor=O;O.prototype.f=function(a){return a};
var P=[-180,-90,180,90],Q=Math.PI*N.radius/180,R=[new O("CRS:84"),new O("EPSG:4326","neu"),new O("urn:ogc:def:crs:EPSG::4326","neu"),new O("urn:ogc:def:crs:EPSG:6.6:4326","neu"),new O("urn:ogc:def:crs:OGC:1.3:CRS84"),new O("urn:ogc:def:crs:OGC:2:84"),new O("http://www.opengis.net/gml/srs/epsg.xml#4326","neu"),new O("urn:x-ogc:def:crs:EPSG:4326","neu")];x(K);x(R);R.forEach(function(a){K.forEach(function(b){y(a,b,L);y(b,a,M)})});var S=angular.module("ngeo",["gettext","ui.date","floatThead"]);k("ngeo.FeatureProperties",{ANGLE:"a",COLOR:"c",IS_CIRCLE:"l",IS_RECTANGLE:"r",IS_TEXT:"t",NAME:"n",OPACITY:"o",AZIMUT:"z",SHOW_MEASURE:"m",SIZE:"s",STROKE:"k"});k("ngeo.GeometryType",{CIRCLE:"Circle",LINE_STRING:"LineString",POINT:"Point",POLYGON:"Polygon",RECTANGLE:"Rectangle",TEXT:"Text"});function T(){}T.prototype.g=function(a){var b=new Date(a.minValue),c=new Date(a.maxValue),d=a.minDefValue?new Date(a.minDefValue):b,e=a.maxDefValue?new Date(a.maxDefValue):c;return{s:b.getTime(),o:c.getTime(),values:"range"===a.mode?[d.getTime(),e.getTime()]:d.getTime()}};T.prototype.getOptions=T.prototype.g;T.prototype.getUTCDate=function(a){return new Date(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate())};T.prototype.getUTCDate=T.prototype.getUTCDate;S.service("ngeoTime",T);S.value("ngeoDatePickerTemplateUrl",function(a,b){a=b.ngeoDatePickerTemplateUrl;return void 0!==a?a:"ngeo/datepicker.html"});
function U(a,b){return{scope:{onDateSelected:"&",time:"="},bindToController:!0,controller:"ngeoDatePickerController",controllerAs:"datepickerCtrl",restrict:"AE",templateUrl:a,link:function(a,d,e,f){a=f.l.getCurrentLanguage();$.datepicker.setDefaults($.datepicker.regional[a]);f.sdateOptions=angular.extend({},f.sdateOptions,{onClose:function(a){a&&$(d[0]).find('input[name="edate"]').datepicker("option","minDate",a)}});f.edateOptions=angular.extend({},f.edateOptions,{onClose:function(a){a&&$(d[0]).find('input[name="sdate"]').datepicker("option",
"maxDate",a)}});angular.element("body").on("hidden.bs.popover",function(){var a=angular.element("#ui-datepicker-div");a&&"block"===a.css("display")&&$(d[0]).find('input[name$="date"]').datepicker("hide")});b(function(){angular.element("#ui-datepicker-div").on("mousedown",function(a){a.stopPropagation()})})}}}U.$inject=["ngeoDatePickerTemplateUrl","$timeout"];S.directive("ngeoDatePicker",U);
function V(a,b,c){this.c=c;c=this.c.g(this.time);this.l=b.get("gettextCatalog");this.isModeRange="range"===this.time.mode;this.b=new Date(c.s);this.a=new Date(c.o);this.edateOptions={minDate:this.b,maxDate:this.a,changeMonth:!0,changeYear:!0};this.sdateOptions={minDate:this.b,maxDate:this.a,changeMonth:!0,changeYear:!0};this.isModeRange?(this.sdate=new Date(c.values[0]),this.edate=new Date(c.values[1])):this.sdate=new Date(c.values);a.$watchGroup(["datepickerCtrl.sdate","datepickerCtrl.edate"],function(a){var b=
a[0];a=a[1];if(angular.isDate(b)&&(!this.isModeRange||angular.isDate(a)))this.onDateSelected({time:{start:b.getTime(),end:a?a.getTime():null}})}.bind(this))}k("ngeo.DatePickerController",V);V.$inject=["$scope","$injector","ngeoTime"];S.controller("ngeoDatePickerController",V);var W=angular.module("app",["ngeo"]);function X(){this.timeRangeMode={widget:"datepicker",maxValue:"2013-12-31T00:00:00Z",minValue:"2006-01-01T00:00:00Z",maxDefValue:null,minDefValue:null,mode:"range",interval:[0,1,0,0]};this.timeValueMode={widget:"datepicker",maxValue:"2015-12-31T00:00:00Z",minValue:"2014-01-01T00:00:00Z",maxDefValue:null,minDefValue:null,mode:"value",interval:[0,1,0,0]};this.onDateSelected=function(a){this.value=a}}X.$inject=["ngeoTime"];W.controller("MainController",X);}).call(window);
//# sourceMappingURL=datepicker.js.map
