(function(){'use strict';var aa=this,g="closure_uid_"+(1E9*Math.random()>>>0),k=0;function l(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b};function n(a,b){a.prototype=Object.create(b.prototype);a.prototype.constructor=a}function p(){};function ba(){};function q(a){this.type=a;this.target=null}q.prototype.preventDefault=q.prototype.stopPropagation=function(){this.C=!0};function r(){this.g={};this.a={};this.f={}}n(r,ba);r.prototype.addEventListener=function(a,b){var c=this.f[a];c||(c=this.f[a]=[]);-1===c.indexOf(b)&&c.push(b)};function t(a,b){var c="string"===typeof b?new q(b):b;b=c.type;c.target=a;var d=a.f[b];if(d){b in a.a||(a.a[b]=0,a.g[b]=0);++a.a[b];for(var e=0,f=d.length;e<f&&!1!==d[e].call(a,c)&&!c.C;++e);--a.a[b];if(0===a.a[b]){c=a.g[b];for(delete a.g[b];c--;)a.removeEventListener(b,p);delete a.a[b]}}}
r.prototype.removeEventListener=function(a,b){var c=this.f[a];c&&(b=c.indexOf(b),a in this.g?(c[b]=p,++this.g[a]):(c.splice(b,1),0===c.length&&delete this.f[a]))};var ca=function(){var a;"cosh"in Math?a=Math.cosh:a=function(a){a=Math.exp(a);return(a+1/a)/2};return a}();/*

 Latitude/longitude spherical geodesy formulae taken from
 http://www.movable-type.co.uk/scripts/latlong.html
 Licensed under CC-BY-3.0.
*/
function u(a){this.radius=a}function v(a,b){var c=a[1]*Math.PI/180,d=b[1]*Math.PI/180,e=(d-c)/2;a=(b[0]-a[0])*Math.PI/180/2;c=Math.sin(e)*Math.sin(e)+Math.sin(a)*Math.sin(a)*Math.cos(c)*Math.cos(d);return 2*w.radius*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))}
u.prototype.offset=function(a,b,c){var d=a[1]*Math.PI/180;b/=this.radius;var e=Math.asin(Math.sin(d)*Math.cos(b)+Math.cos(d)*Math.sin(b)*Math.cos(c));return[180*(a[0]*Math.PI/180+Math.atan2(Math.sin(c)*Math.sin(b)*Math.cos(d),Math.cos(b)-Math.sin(d)*Math.sin(e)))/Math.PI,180*e/Math.PI]};var w=new u(6370997);var x={};x.degrees=2*Math.PI*w.radius/360;x.ft=.3048;x.m=1;x["us-ft"]=1200/3937;function y(a){this.a=a.code;this.b=a.units;this.f=void 0!==a.i?a.i:this.g;this.c=a.w;var b=z,c=a.code,d=A||window.proj4;if("function"==typeof d&&void 0===b[c]){var e=d.defs(c);if(void 0!==e){void 0===a.w&&(this.c=e.to_meter);void 0===a.units&&(this.b=e.units);var f,h;for(f in b)if(a=d.defs(f),void 0!==a)if(b=B(f),a===e)C([b,this]);else{h=d(f,c);a=h.forward;h=h.inverse;var b=B(b),m=B(this);D(b,m,E(a));D(m,b,E(h))}}}}
y.prototype.g=function(a,b){if("degrees"==this.b)return a;var c=B("EPSG:4326"),d=this.a,c=c.a,e;d in F&&c in F[d]&&(e=F[d][c]);void 0===e&&(e=da);a=[b[0]-a/2,b[1],b[0]+a/2,b[1],b[0],b[1]-a/2,b[0],b[1]+a/2];a=e(a,a,2);e=(v(a.slice(0,2),a.slice(2,4))+v(a.slice(4,6),a.slice(6,8)))/2;a=this.c||x[this.b];void 0!==a&&(e/=a);return e};y.prototype.i=function(a,b){return this.f(a,b)};var z={},F={},A=null;function C(a){ea(a);a.forEach(function(b){a.forEach(function(a){b!==a&&D(b,a,G)})})}
function H(a){z[a.a]=a;D(a,a,G)}function ea(a){var b=[];a.forEach(function(a){b.push(H(a))})}function D(a,b,c){a=a.a;b=b.a;a in F||(F[a]={});F[a][b]=c}function E(a){return function(b,c,d){var e=b.length;d=void 0!==d?d:2;c=void 0!==c?c:Array(e);var f,h;for(h=0;h<e;h+=d)for(f=a([b[h],b[h+1]]),c[h]=f[0],c[h+1]=f[1],f=d-1;2<=f;--f)c[h+f]=b[h+f];return c}}
function B(a){var b;if(a instanceof y)b=a;else if("string"===typeof a){b=z[a];var c=A||window.proj4;void 0===b&&"function"==typeof c&&void 0!==c.defs(a)&&(b=new y({code:a}),H(b))}return b||null}function da(a,b){if(void 0!==b&&a!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}return a}function G(a,b){if(void 0!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}else a=a.slice();return a};(function(){if(!("HTMLCanvasElement"in window))return!1;try{return document.createElement("CANVAS").getContext("2d")?!0:!1}catch(a){return!1}})();navigator.userAgent.match("CriOS");try{new MouseEvent("click",{buttons:1})}catch(a){};function I(a){y.call(this,{code:a,units:"m",extent:fa,global:!0,D:ga})}n(I,y);I.prototype.i=function(a,b){return a/ca(b[1]/6378137)};var J=6378137*Math.PI,fa=[-J,-J,J,J],ga=[-180,-85,180,85],K="EPSG:3857 EPSG:102100 EPSG:102113 EPSG:900913 urn:ogc:def:crs:EPSG:6.18:3:3857 urn:ogc:def:crs:EPSG::3857 http://www.opengis.net/gml/srs/epsg.xml#3857".split(" ").map(function(a){return new I(a)});
function ha(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c){b[e]=J*a[e]/180;var f=6378137*Math.log(Math.tan(Math.PI*(a[e+1]+90)/360));f>J?f=J:f<-J&&(f=-J);b[e+1]=f}return b}function ia(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c)b[e]=180*a[e]/J,b[e+1]=360*Math.atan(Math.exp(a[e+1]/6378137))/Math.PI-90;return b};var ja=new u(6378137);function L(a,b){y.call(this,{code:a,units:"degrees",extent:N,F:b,global:!0,w:ka,D:N})}n(L,y);L.prototype.i=function(a){return a};var N=[-180,-90,180,90],ka=Math.PI*ja.radius/180,O=[new L("CRS:84"),new L("EPSG:4326","neu"),new L("urn:ogc:def:crs:EPSG::4326","neu"),new L("urn:ogc:def:crs:EPSG:6.6:4326","neu"),new L("urn:ogc:def:crs:OGC:1.3:CRS84"),new L("urn:ogc:def:crs:OGC:2:84"),new L("http://www.opengis.net/gml/srs/epsg.xml#4326","neu"),new L("urn:x-ogc:def:crs:EPSG:4326","neu")];C(K);C(O);O.forEach(function(a){K.forEach(function(b){D(a,b,ha);D(b,a,ia)})});var P=angular.module("ngeo",["gettext","ui.date","floatThead"]);l("ngeo.FeatureProperties",{ANGLE:"a",COLOR:"c",IS_CIRCLE:"l",IS_RECTANGLE:"r",IS_TEXT:"t",NAME:"n",OPACITY:"o",AZIMUT:"z",SHOW_MEASURE:"m",SIZE:"s",STROKE:"k"});l("ngeo.GeometryType",{CIRCLE:"Circle",LINE_STRING:"LineString",POINT:"Point",POLYGON:"Polygon",RECTANGLE:"Rectangle",TEXT:"Text"});var Q=angular.module("gmf",[P.name,"gettext","ngAnimate","ngTouch","ngSanitize","tmh.dynamicLocale","ui.date","ui.slider"]);Q.config(["tmhDynamicLocaleProvider","angularLocaleScript",function(a,b){a.localeLocationPattern(b)}]);l("gmf.DATALAYERGROUP_NAME","data");l("gmf.COORDINATES_LAYER_NAME","gmfCoordinatesLayerName");function la(a){return Array.prototype.join.call(arguments,"")};function R(a,b){if(0<=a.indexOf("#")||0<=a.indexOf("?"))throw Error("goog.uri.utils: Fragment or query identifiers are not supported: ["+a+"]");var c=a.length-1;0<=c&&a.indexOf("/",c)==c&&(a=a.substr(0,a.length-1));0==b.lastIndexOf("/",0)&&(b=b.substr(1));return la(a,"/",b)};Q.value("gmfUser",{functionalities:null,is_password_changed:null,role_id:null,role_name:null,username:null});function S(a){q.call(this,a)}n(S,q);function T(a,b,c){r.call(this);this.b=a;this.c=b;this.s=c;a=R(this.c,"loginuser");this.b.get(a,{withCredentials:!0}).then(this.v.bind(this,!0))}n(T,r);T.$inject=["$http","authenticationBaseUrl","gmfUser"];
T.prototype.h=function(a,b,c){var d=R(this.c,"loginchange");return this.b.post(d,$.param({oldPassword:a,newPassword:b,confirmNewPassword:c}),{headers:{"Content-Type":"application/x-www-form-urlencoded"},withCredentials:!0})};T.prototype.changePassword=T.prototype.h;T.prototype.j=function(a,b){var c=R(this.c,"login");return this.b.post(c,$.param({login:a,password:b}),{headers:{"Content-Type":"application/x-www-form-urlencoded"},withCredentials:!0}).then(this.v.bind(this,!1))};T.prototype.login=T.prototype.j;
T.prototype.l=function(){var a=R(this.c,"logout");return this.b.get(a,{withCredentials:!0}).then(this.B.bind(this))};T.prototype.logout=T.prototype.l;T.prototype.o=function(a){var b=R(this.c,"loginresetpassword"),c=function(a){return a.data}.bind(this);return this.b.post(b,$.param({login:a}),{headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(c)};T.prototype.resetPassword=T.prototype.o;
T.prototype.v=function(a,b){var c=b.data,d;for(d in c)this.s[d]=c[d];!a&&void 0!==c.username&&t(this,new S("login"));a&&t(this,new S("ready"));return b};T.prototype.B=function(){for(var a in this.s)this.s[a]=null;t(this,new S("logout"))};Q.service("gmfAuthentication",T);l("ngeo.MessageType",{ERROR:"error",INFORMATION:"information",SUCCESS:"success",WARNING:"warning"});function U(){}U.prototype.show=function(a){V(this,a).forEach(this.f,this)};U.prototype.show=U.prototype.show;U.prototype.error=function(a){this.show(V(this,a,"error"))};U.prototype.error=U.prototype.error;U.prototype.info=function(a){this.show(V(this,a,"information"))};U.prototype.info=U.prototype.info;U.prototype.success=function(a){this.show(V(this,a,"success"))};U.prototype.success=U.prototype.success;
U.prototype.warn=function(a){this.show(V(this,a,"warning"))};U.prototype.warn=U.prototype.warn;function V(a,b,c){var d=[],e=null;"string"===typeof b?d.push({msg:b,type:void 0!==c?c:"information"}):Array.isArray(b)?b.forEach(function(a){"string"===typeof b?e={msg:a,type:void 0!==c?c:"information"}:(e=a,void 0!==c&&(e.type=c));d.push(e)},a):(e=b,void 0!==c&&(e.type=c),void 0===e.type&&(e.type="information"),d.push(e));return d};function W(a){this.b=a;a=angular.element('<div class="ngeo-notification"></div>');angular.element(document.body).append(a);this.c=a;this.a={}}n(W,U);W.$inject=["$timeout"];W.prototype.notify=function(a){this.show(a)};W.prototype.notify=W.prototype.notify;W.prototype.clear=function(){for(var a in this.a){var b=this.a[parseInt(a,10)],c=b.A,b=b.promise,d=c[g]||(c[g]=++k);c.alert("close");this.b.cancel(b);delete this.a[d]}};W.prototype.clear=W.prototype.clear;
W.prototype.f=function(a){var b=["alert","fade"];switch(a.type){case "error":b.push("alert-danger");break;case "information":b.push("alert-info");break;case "success":b.push("alert-success");break;case "warning":b.push("alert-warning")}var c=angular.element('<div class="'+b.join(" ")+'"></div>'),d;a.target?d=angular.element(a.target):d=this.c;d.append(c);c.html(a.msg).addClass("in");a=void 0!==a.delay?a.delay:7E3;var b={A:c},e=c[g]||(c[g]=++k);b.promise=this.b(function(){c.alert("close");delete this.a[e]}.bind(this),
a);this.a[e]=b};P.service("ngeoNotification",W);function X(){return{template:'<div class="modal fade" tabindex="-1" role="dialog"><div class="modal-dialog"><div class="modal-content"></div></div></div>',restrict:"E",require:"ngModel",transclude:!0,link:function(a,b,c,d,e){function f(){M=a.$new();e(M,function(a){m.find(".modal-content").append(a)})}function h(){M.$destroy();m.find(".modal-content").empty()}var m=b.children();b="true"===c.ngeoModalDestroyContentOnHide;var M=a.$new();angular.element(document.body).append(m);d.$render=function(){m.modal(d.$viewValue?
"show":"hide")};m.on("shown.bs.modal hidden.bs.modal",function(b){var c=b.type;a.$apply(function(){d.$setViewValue("shown"==c)})});b?(m.on("hide.bs.modal",h),m.on("show.bs.modal",f)):m.find(".modal-content").append(e())}}}X.$inject=["$parse"];P.directive("ngeoModal",X);Q.value("gmfAuthenticationTemplateUrl",function(a,b){a=b.gmfAuthenticationTemplateurl;return void 0!==a?a:"gmf/authentication.html"});function Y(a){return{scope:!0,controller:"GmfAuthenticationController",controllerAs:"authCtrl",templateUrl:a}}Y.$inject=["gmfAuthenticationTemplateUrl"];Q.directive("gmfAuthentication",Y);
function Z(a,b,c,d,e){this.gmfUser=d;this.a=a;this.f=c;this.g=e;this.error=this.resetPasswordModalShown=this.changePasswordModalShown=this.changingPassword=!1;this.newPwdConfVal=this.newPwdVal=this.oldPwdVal=this.pwdVal=this.loginVal=""}Z.$inject=["gettextCatalog","$scope","gmfAuthentication","gmfUser","ngeoNotification"];
Z.prototype.h=function(){var a=this.oldPwdVal,b=this.newPwdVal,c=this.newPwdConfVal,d=[];""===a&&d.push(this.a.getString("The old password is required."));""===b&&d.push(this.a.getString("The new password is required."));""===c&&d.push(this.a.getString("The password confirmation is required."));d.length?this.b(d):(a===b&&d.push(this.a.getString("The old and new passwords are the same.")),b!==c&&d.push(this.a.getString("The passwords don't match.")),d.length?this.b(d):(d=this.a.getString("Incorrect old password."),
this.f.h(a,b,c).then(function(){this.changePasswordModalShown=!0;this.u()}.bind(this),this.b.bind(this,d))))};Z.prototype.changePassword=Z.prototype.h;Z.prototype.j=function(){var a=[];""===this.loginVal&&a.push(this.a.getString("The username is required."));""===this.pwdVal&&a.push(this.a.getString("The password is required."));a.length?this.b(a):(a=this.a.getString("Incorrect username or password."),this.f.j(this.loginVal,this.pwdVal).then(this.c.bind(this),this.b.bind(this,a)))};
Z.prototype.login=Z.prototype.j;Z.prototype.l=function(){var a=this.a.getString("Could not log out.");this.f.l().then(this.c.bind(this),this.b.bind(this,a))};Z.prototype.logout=Z.prototype.l;Z.prototype.o=function(){if(this.loginVal){var a=this.a.getString("An error occured while reseting the password."),b=function(){this.resetPasswordModalShown=!0;this.c()}.bind(this);this.f.o(this.loginVal).then(b,this.b.bind(this,a))}else this.b(this.a.getString("Please, input a login..."))};
Z.prototype.resetPassword=Z.prototype.o;Z.prototype.u=function(){this.c();this.changingPassword=!1;this.newPwdConfVal=this.newPwdVal=this.oldPwdVal=""};Z.prototype.changePasswordReset=Z.prototype.u;Z.prototype.b=function(a){this.error&&this.c();this.error=!0;var b=angular.element(".gmf-authentication-error");Array.isArray(a)||(a=[a]);a.forEach(function(a){this.g.notify({msg:a,target:b,type:"error"})},this)};Z.prototype.c=function(){this.g.clear();this.error=!1};
Q.controller("GmfAuthenticationController",Z);var ma=angular.module("gmfapp",["gmf"]);ma.value("authenticationBaseUrl","https://geomapfish-demo.camptocamp.net/2.1/wsgi");ma.controller("MainController",function(){});}).call(window);
//# sourceMappingURL=authentication.js.map
