(function(){'use strict';var h=this;function l(a,b){a=a.split(".");var c=h;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b};function m(a){this.type=a;this.target=null}m.prototype.preventDefault=m.prototype.stopPropagation=function(){};var n=function(){var a;"cosh"in Math?a=Math.cosh:a=function(a){a=Math.exp(a);return(a+1/a)/2};return a}();/*

 Latitude/longitude spherical geodesy formulae taken from
 http://www.movable-type.co.uk/scripts/latlong.html
 Licensed under CC-BY-3.0.
*/
function p(a){this.radius=a}function q(a,b){var c=a[1]*Math.PI/180,d=b[1]*Math.PI/180,e=(d-c)/2;a=(b[0]-a[0])*Math.PI/180/2;c=Math.sin(e)*Math.sin(e)+Math.sin(a)*Math.sin(a)*Math.cos(c)*Math.cos(d);return 2*r.radius*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))}
p.prototype.offset=function(a,b,c){var d=a[1]*Math.PI/180;b/=this.radius;var e=Math.asin(Math.sin(d)*Math.cos(b)+Math.cos(d)*Math.sin(b)*Math.cos(c));return[180*(a[0]*Math.PI/180+Math.atan2(Math.sin(c)*Math.sin(b)*Math.cos(d),Math.cos(b)-Math.sin(d)*Math.sin(e)))/Math.PI,180*e/Math.PI]};var r=new p(6370997);var t={};t.degrees=2*Math.PI*r.radius/360;t.ft=.3048;t.m=1;t["us-ft"]=1200/3937;function u(a){this.a=a.code;this.b=a.units;this.j=void 0!==a.f?a.f:this.l;this.c=a.i;var b=v,c=a.code,d=w||window.proj4;if("function"==typeof d&&void 0===b[c]){var e=d.defs(c);if(void 0!==e){void 0===a.i&&(this.c=e.to_meter);void 0===a.units&&(this.b=e.units);var f,g;for(f in b)if(a=d.defs(f),void 0!==a)if(b=x(f),a===e)y([b,this]);else{g=d(f,c);a=g.forward;g=g.inverse;var b=x(b),k=x(this);z(b,k,A(a));z(k,b,A(g))}}}}
u.prototype.l=function(a,b){if("degrees"==this.b)return a;var c=x("EPSG:4326"),d=this.a,c=c.a,e;d in C&&c in C[d]&&(e=C[d][c]);void 0===e&&(e=D);a=[b[0]-a/2,b[1],b[0]+a/2,b[1],b[0],b[1]-a/2,b[0],b[1]+a/2];a=e(a,a,2);e=(q(a.slice(0,2),a.slice(2,4))+q(a.slice(4,6),a.slice(6,8)))/2;a=this.c||t[this.b];void 0!==a&&(e/=a);return e};u.prototype.f=function(a,b){return this.j(a,b)};var v={},C={},w=null;function y(a){E(a);a.forEach(function(b){a.forEach(function(a){b!==a&&z(b,a,F)})})}
function G(a){v[a.a]=a;z(a,a,F)}function E(a){var b=[];a.forEach(function(a){b.push(G(a))})}function z(a,b,c){a=a.a;b=b.a;a in C||(C[a]={});C[a][b]=c}function A(a){return function(b,c,d){var e=b.length;d=void 0!==d?d:2;c=void 0!==c?c:Array(e);var f,g;for(g=0;g<e;g+=d)for(f=a([b[g],b[g+1]]),c[g]=f[0],c[g+1]=f[1],f=d-1;2<=f;--f)c[g+f]=b[g+f];return c}}
function x(a){var b;if(a instanceof u)b=a;else if("string"===typeof a){b=v[a];var c=w||window.proj4;void 0===b&&"function"==typeof c&&void 0!==c.defs(a)&&(b=new u({code:a}),G(b))}return b||null}function D(a,b){if(void 0!==b&&a!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}return a}function F(a,b){if(void 0!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}else a=a.slice();return a};(function(){if(!("HTMLCanvasElement"in window))return!1;try{return document.createElement("CANVAS").getContext("2d")?!0:!1}catch(a){return!1}})();navigator.userAgent.match("CriOS");try{new MouseEvent("click",{buttons:1})}catch(a){};function H(a){u.call(this,{code:a,units:"m",extent:I,global:!0,o:J})}H.prototype=Object.create(u.prototype);H.prototype.constructor=H;H.prototype.f=function(a,b){return a/n(b[1]/6378137)};var K=6378137*Math.PI,I=[-K,-K,K,K],J=[-180,-85,180,85],L="EPSG:3857 EPSG:102100 EPSG:102113 EPSG:900913 urn:ogc:def:crs:EPSG:6.18:3:3857 urn:ogc:def:crs:EPSG::3857 http://www.opengis.net/gml/srs/epsg.xml#3857".split(" ").map(function(a){return new H(a)});
function M(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c){b[e]=K*a[e]/180;var f=6378137*Math.log(Math.tan(Math.PI*(a[e+1]+90)/360));f>K?f=K:f<-K&&(f=-K);b[e+1]=f}return b}function N(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c)b[e]=180*a[e]/K,b[e+1]=360*Math.atan(Math.exp(a[e+1]/6378137))/Math.PI-90;return b};var O=new p(6378137);function P(a,b){u.call(this,{code:a,units:"degrees",extent:Q,s:b,global:!0,i:R,o:Q})}P.prototype=Object.create(u.prototype);P.prototype.constructor=P;P.prototype.f=function(a){return a};
var Q=[-180,-90,180,90],R=Math.PI*O.radius/180,S=[new P("CRS:84"),new P("EPSG:4326","neu"),new P("urn:ogc:def:crs:EPSG::4326","neu"),new P("urn:ogc:def:crs:EPSG:6.6:4326","neu"),new P("urn:ogc:def:crs:OGC:1.3:CRS84"),new P("urn:ogc:def:crs:OGC:2:84"),new P("http://www.opengis.net/gml/srs/epsg.xml#4326","neu"),new P("urn:x-ogc:def:crs:EPSG:4326","neu")];y(L);y(S);S.forEach(function(a){L.forEach(function(b){z(a,b,M);z(b,a,N)})});var T=angular.module("ngeo",["gettext","ui.date","floatThead"]);l("ngeo.FeatureProperties",{ANGLE:"a",COLOR:"c",IS_CIRCLE:"l",IS_RECTANGLE:"r",IS_TEXT:"t",NAME:"n",OPACITY:"o",AZIMUT:"z",SHOW_MEASURE:"m",SIZE:"s",STROKE:"k"});l("ngeo.GeometryType",{CIRCLE:"Circle",LINE_STRING:"LineString",POINT:"Point",POLYGON:"Polygon",RECTANGLE:"Rectangle",TEXT:"Text"});var U=angular.module("gmf",[T.name,"gettext","ngAnimate","ngTouch","ngSanitize","tmh.dynamicLocale","ui.date","ui.slider"]);U.config(["tmhDynamicLocaleProvider","angularLocaleScript",function(a,b){a.localeLocationPattern(b)}]);l("gmf.DATALAYERGROUP_NAME","data");l("gmf.COORDINATES_LAYER_NAME","gmfCoordinatesLayerName");function V(a,b){this.b=a;this.a=b}l("gmf.ShareService",V);V.$inject=["$http","gmfShortenerCreateUrl"];V.prototype.g=function(a){return this.a?W(this,{url:a}):{data:{short_url:a},status:200}};V.prototype.h=function(a,b,c){a={url:a,email:b};c&&(a.message=c);return W(this,a)};function W(a,b){return a.b.post(a.a,$.param(b),{headers:{"Content-Type":"application/x-www-form-urlencoded"}})}U.service("gmfShareService",V);function X(a,b,c,d,e){this.c=a;this.b=c;this.a=d;this.enableEmail="true"===e.gmfShareEmail;this.permalink=b.v();this.showLenghtWarning=2083<this.permalink.length||2048<b.u();this.errorOnsend=this.successfullySent=!1;this.g()}l("gmf.ShareController",X);X.$inject=["$scope","ngeoLocation","gmfShareService","$q","$attrs"];
X.prototype.g=function(){this.a.when(this.b.g(this.permalink)).then(function(a){this.shortLink=a.data.short_url}.bind(this),function(){this.shortLink=this.permalink;this.errorOnGetShortUrl=!0}.bind(this))};X.prototype.getShortUrl=X.prototype.g;X.prototype.h=function(){function a(){this.successfullySent=!0}function b(){}this.c.gmfShareForm.$valid&&this.a.when(this.b.h(this.permalink,this.email,this.message)).then(a.bind(this),b.bind(this))};X.prototype.sendShortUrl=X.prototype.h;
U.directive("gmfShare",function(){return{restrict:"E",controller:"GmfShareController",controllerAs:"shareCtrl",templateUrl:"gmf/share.html"}});U.controller("GmfShareController",X);function Y(){return{template:'<div class="modal fade" tabindex="-1" role="dialog"><div class="modal-dialog"><div class="modal-content"></div></div></div>',restrict:"E",require:"ngModel",transclude:!0,link:function(a,b,c,d,e){function f(){B=a.$new();e(B,function(a){k.find(".modal-content").append(a)})}function g(){B.$destroy();k.find(".modal-content").empty()}var k=b.children();b="true"===c.ngeoModalDestroyContentOnHide;var B=a.$new();angular.element(document.body).append(k);d.$render=function(){k.modal(d.$viewValue?
"show":"hide")};k.on("shown.bs.modal hidden.bs.modal",function(b){var c=b.type;a.$apply(function(){d.$setViewValue("shown"==c)})});b?(k.on("hide.bs.modal",g),k.on("show.bs.modal",f)):k.find(".modal-content").append(e())}}}Y.$inject=["$parse"];T.directive("ngeoModal",Y);angular.module("gmfapp",["gmf"]).controller("MainController",function(){this.modalShareShown=this.modalShareWithEmailShown=!1});}).call(window);
//# sourceMappingURL=share.js.map
