(function(){'use strict';var h=this;function k(a,b){a=a.split(".");var c=h;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b};function m(a,b){a.prototype=Object.create(b.prototype);a.prototype.constructor=a};function n(a){this.type=a;this.target=null}n.prototype.preventDefault=n.prototype.stopPropagation=function(){};var p=function(){var a;"cosh"in Math?a=Math.cosh:a=function(a){a=Math.exp(a);return(a+1/a)/2};return a}();/*

 Latitude/longitude spherical geodesy formulae taken from
 http://www.movable-type.co.uk/scripts/latlong.html
 Licensed under CC-BY-3.0.
*/
function q(a){this.radius=a}function r(a,b){var c=a[1]*Math.PI/180,d=b[1]*Math.PI/180,e=(d-c)/2;a=(b[0]-a[0])*Math.PI/180/2;c=Math.sin(e)*Math.sin(e)+Math.sin(a)*Math.sin(a)*Math.cos(c)*Math.cos(d);return 2*t.radius*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))}
q.prototype.offset=function(a,b,c){var d=a[1]*Math.PI/180;b/=this.radius;var e=Math.asin(Math.sin(d)*Math.cos(b)+Math.cos(d)*Math.sin(b)*Math.cos(c));return[180*(a[0]*Math.PI/180+Math.atan2(Math.sin(c)*Math.sin(b)*Math.cos(d),Math.cos(b)-Math.sin(d)*Math.sin(e)))/Math.PI,180*e/Math.PI]};var t=new q(6370997);var u={};u.degrees=2*Math.PI*t.radius/360;u.ft=.3048;u.m=1;u["us-ft"]=1200/3937;function v(a){this.a=a.code;this.b=a.units;this.j=void 0!==a.c?a.c:this.l;this.f=a.i;var b=w,c=a.code,d=x||window.proj4;if("function"==typeof d&&void 0===b[c]){var e=d.defs(c);if(void 0!==e){void 0===a.i&&(this.f=e.to_meter);void 0===a.units&&(this.b=e.units);var f,g;for(f in b)if(a=d.defs(f),void 0!==a)if(b=y(f),a===e)z([b,this]);else{g=d(f,c);a=g.forward;g=g.inverse;var b=y(b),l=y(this);A(b,l,B(a));A(l,b,B(g))}}}}
v.prototype.l=function(a,b){if("degrees"==this.b)return a;var c=y("EPSG:4326"),d=this.a,c=c.a,e;d in C&&c in C[d]&&(e=C[d][c]);void 0===e&&(e=D);a=[b[0]-a/2,b[1],b[0]+a/2,b[1],b[0],b[1]-a/2,b[0],b[1]+a/2];a=e(a,a,2);e=(r(a.slice(0,2),a.slice(2,4))+r(a.slice(4,6),a.slice(6,8)))/2;a=this.f||u[this.b];void 0!==a&&(e/=a);return e};v.prototype.c=function(a,b){return this.j(a,b)};var w={},C={},x=null;function z(a){E(a);a.forEach(function(b){a.forEach(function(a){b!==a&&A(b,a,F)})})}
function G(a){w[a.a]=a;A(a,a,F)}function E(a){var b=[];a.forEach(function(a){b.push(G(a))})}function A(a,b,c){a=a.a;b=b.a;a in C||(C[a]={});C[a][b]=c}function B(a){return function(b,c,d){var e=b.length;d=void 0!==d?d:2;c=void 0!==c?c:Array(e);var f,g;for(g=0;g<e;g+=d)for(f=a([b[g],b[g+1]]),c[g]=f[0],c[g+1]=f[1],f=d-1;2<=f;--f)c[g+f]=b[g+f];return c}}
function y(a){var b;if(a instanceof v)b=a;else if("string"===typeof a){b=w[a];var c=x||window.proj4;void 0===b&&"function"==typeof c&&void 0!==c.defs(a)&&(b=new v({code:a}),G(b))}return b||null}function D(a,b){if(void 0!==b&&a!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}return a}function F(a,b){if(void 0!==b){for(var c=0,d=a.length;c<d;++c)b[c]=a[c];a=b}else a=a.slice();return a};(function(){if(!("HTMLCanvasElement"in window))return!1;try{return document.createElement("CANVAS").getContext("2d")?!0:!1}catch(a){return!1}})();navigator.userAgent.match("CriOS");try{new MouseEvent("click",{buttons:1})}catch(a){};function H(a){v.call(this,{code:a,units:"m",extent:I,global:!0,u:J})}m(H,v);H.prototype.c=function(a,b){return a/p(b[1]/6378137)};var K=6378137*Math.PI,I=[-K,-K,K,K],J=[-180,-85,180,85],L="EPSG:3857 EPSG:102100 EPSG:102113 EPSG:900913 urn:ogc:def:crs:EPSG:6.18:3:3857 urn:ogc:def:crs:EPSG::3857 http://www.opengis.net/gml/srs/epsg.xml#3857".split(" ").map(function(a){return new H(a)});
function M(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c){b[e]=K*a[e]/180;var f=6378137*Math.log(Math.tan(Math.PI*(a[e+1]+90)/360));f>K?f=K:f<-K&&(f=-K);b[e+1]=f}return b}function aa(a,b,c){var d=a.length;c=1<c?c:2;void 0===b&&(2<c?b=a.slice():b=Array(d));for(var e=0;e<d;e+=c)b[e]=180*a[e]/K,b[e+1]=360*Math.atan(Math.exp(a[e+1]/6378137))/Math.PI-90;return b};var ba=new q(6378137);function N(a,b){v.call(this,{code:a,units:"degrees",extent:O,v:b,global:!0,i:ca,u:O})}m(N,v);N.prototype.c=function(a){return a};var O=[-180,-90,180,90],ca=Math.PI*ba.radius/180,P=[new N("CRS:84"),new N("EPSG:4326","neu"),new N("urn:ogc:def:crs:EPSG::4326","neu"),new N("urn:ogc:def:crs:EPSG:6.6:4326","neu"),new N("urn:ogc:def:crs:OGC:1.3:CRS84"),new N("urn:ogc:def:crs:OGC:2:84"),new N("http://www.opengis.net/gml/srs/epsg.xml#4326","neu"),new N("urn:x-ogc:def:crs:EPSG:4326","neu")];z(L);z(P);P.forEach(function(a){L.forEach(function(b){A(a,b,M);A(b,a,aa)})});var Q=angular.module("ngeo",["gettext","ui.date","floatThead"]);k("ngeo.FeatureProperties",{ANGLE:"a",COLOR:"c",IS_CIRCLE:"l",IS_RECTANGLE:"r",IS_TEXT:"t",NAME:"n",OPACITY:"o",AZIMUT:"z",SHOW_MEASURE:"m",SIZE:"s",STROKE:"k"});k("ngeo.GeometryType",{CIRCLE:"Circle",LINE_STRING:"LineString",POINT:"Point",POLYGON:"Polygon",RECTANGLE:"Rectangle",TEXT:"Text"});var S=angular.module("gmf",[Q.name,"gettext","ngAnimate","ngTouch","ngSanitize","tmh.dynamicLocale","ui.date","ui.slider"]);S.config(["tmhDynamicLocaleProvider","angularLocaleScript",function(a,b){a.localeLocationPattern(b)}]);k("gmf.DATALAYERGROUP_NAME","data");k("gmf.COORDINATES_LAYER_NAME","gmfCoordinatesLayerName");function T(){}T.prototype.h=function(a){var b=new Date(a.minValue),c=new Date(a.maxValue),d=a.minDefValue?new Date(a.minDefValue):b,e=a.maxDefValue?new Date(a.maxDefValue):c;return{s:b.getTime(),o:c.getTime(),values:"range"===a.mode?[d.getTime(),e.getTime()]:d.getTime()}};T.prototype.getOptions=T.prototype.h;T.prototype.getUTCDate=function(a){return new Date(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate())};T.prototype.getUTCDate=T.prototype.getUTCDate;Q.service("ngeoTime",T);function U(a){this.a=a}m(U,T);U.$inject=["$filter"];function V(a,b,c,d){b=new Date(b);d=d?"UTC":void 0;switch(c){case "year":return a.a("date")(b,"yyyy",d);case "month":return a.a("date")(b,"yyyy-MM",d);case "day":return a.a("date")(b,"yyyy-MM-dd",d);default:return b.toISOString().replace(/\.\d{3}/,"")}}U.prototype.g=function(a,b,c){return"range"===a.mode?V(this,b.start,a.resolution,c)+"/"+V(this,b.end,a.resolution,c):V(this,b.start,a.resolution,c)};U.prototype.formatWMSTimeParam=U.prototype.g;
S.service("gmfWMSTime",U);function W(){return{scope:{onDateSelected:"&gmfTimeSliderOnDateSelected",time:"=gmfTimeSliderTime"},bindToController:!0,controller:"gmfTimeSliderController",controllerAs:"sliderCtrl",restrict:"AE",templateUrl:"gmf/timeslider.html",link:function(a,b,c,d){function e(b,c){c.values?(b=new Date(X(d,c.values[0])),c=new Date(X(d,c.values[1])),d.dates=[b,c],c={start:b.getTime(),end:c.getTime()}):(b=new Date(X(d,c.value)),d.dates=b,c={start:b.getTime()});a.$apply();return c}d.sliderOptions.stop=function(a,
b){d.onDateSelected({time:e(0,b)})};d.sliderOptions.slide=e}}}W.$inject=["$timeout","$filter"];function Y(a,b){this.b=b;a=this.b.h(this.time);this.isModeRange="range"===this.time.mode;this.minValue=a.s;this.maxValue=a.o;this.a=da(this);this.sliderOptions={range:this.isModeRange,min:this.minValue,max:this.maxValue};this.dates=this.isModeRange?[a.values[0],a.values[1]]:a.values}k("gmf.TimeSliderController",Y);Y.$inject=["$scope","gmfWMSTime"];
function da(a){var b=a.time,c=null,d=new Date(a.minValue);a=new Date(a.maxValue);if(b.values)c=[],b.values.forEach(function(a){c.push((new Date(a)).getTime())});else{var e=new Date(d.getTime());e.setFullYear(d.getFullYear()+1024*b.interval[0]);e.setMonth(d.getMonth()+1024*b.interval[1],d.getDate()+1024*b.interval[2]);e.setSeconds(d.getSeconds()+1024*b.interval[3]);if(e>a)for(c=[],e=0;;e++){var f=new Date(d.getTime());f.setFullYear(d.getFullYear()+e*b.interval[0]);f.setMonth(d.getMonth()+e*b.interval[1],
d.getDate()+e*b.interval[2]);f.setSeconds(d.getSeconds()+e*b.interval[3]);if(f<=a)c.push(f.getTime());else break}}return c}
function X(a,b){if(b<=a.minValue)return a.minValue;if(b>=a.maxValue)return a.maxValue;if(a.a){for(var c,d=0,e=a.a.length-1;1<e-d;)c=Math.floor((d+e)/2),a.a[c]>=b?e=c:d=c;return a.a[Math.abs(a.a[d]-b)<Math.abs(a.a[e]-b)?d:e]}b=new Date(b);c=new Date(a.minValue);for(var d=new Date(a.minValue),e=new Date(a.maxValue),f=Math.abs(b-d),g=1;;g++){var l=new Date(c.getTime());l.setFullYear(c.getFullYear()+g*a.time.interval[0]);l.setMonth(c.getMonth()+g*a.time.interval[1],c.getDate()+g*a.time.interval[2]);l.setSeconds(c.getSeconds()+
g*a.time.interval[3]);if(l>e)break;var R=Math.abs(b-l);if(R<=f)d=l,f=R;else break}return d.getTime()}S.controller("gmfTimeSliderController",Y);S.directive("gmfTimeSlider",W);var ea=angular.module("gmfapp",["gmf"]);
function Z(a,b){this.a=b;this.wmsTimeRangeMode={widget:"slider",maxValue:"2013-12-31T00:00:00Z",minValue:"2006-01-01T00:00:00Z",maxDefValue:null,minDefValue:null,resolution:"day",mode:"range",interval:[0,1,0,0]};this.wmsTimeValueMode={widget:"slider",maxValue:"2015-12-31T00:00:00Z",minValue:"2014-01-01T00:00:00Z",maxDefValue:null,minDefValue:null,resolution:"year",mode:"value",interval:[0,0,1,0]};this.onDateSelected=function(b){this.sliderValue=this.a.g(this.wmsTimeValueMode,b);a.$digest()}}
Z.$inject=["$scope","gmfWMSTime"];ea.controller("MainController",Z);}).call(window);
//# sourceMappingURL=timeslider.js.map
